---
driver:
  name: gce
  project: dazzlingwrench
  region: us-east1
  preemptible: true

provisioner:
  name: chef_zero

transport:
  username: kitchenuser

platforms:
  - name: windows2008
    driver:
      email: 954209166228-compute@developer.gserviceaccount.com
      image_project: windows-cloud
      image_family: windows-2008-r2
      disk_size: 50
      metadata:
        windows-startup-script-ps1: |
          winrm quickconfig -q
          winrm s winrm/config/winrs '@{MaxMemoryPerShellMB="512"}'
          winrm s winrm/config '@{MaxTimeoutms="1800000"}'
          winrm s winrm/config/service '@{AllowUnencrypted="true"}'
          winrm s winrm/config/service/auth '@{Basic="true"}'
          netsh firewall add portopening TCP 5985 "Port 5985"
          winrm s winrm/config/listener?Address=*+Transport=HTTP '@{Port="5985"}'
          get-service winrm
  - name: windows2012
    driver:
      email: 954209166228-compute@developer.gserviceaccount.com
      image_project: windows-cloud
      image_family: windows-2012-r2
      disk_size: 50
      metadata:
        windows-startup-script-ps1: |
          winrm quickconfig -q
          winrm s winrm/config/winrs '@{MaxMemoryPerShellMB="512"}'
          winrm s winrm/config '@{MaxTimeoutms="1800000"}'
          winrm s winrm/config/service '@{AllowUnencrypted="true"}'
          winrm s winrm/config/service/auth '@{Basic="true"}'
          netsh firewall add portopening TCP 5985 "Port 5985"
          winrm s winrm/config/listener?Address=*+Transport=HTTP '@{Port="5985"}'
          get-service winrm
  - name: windows2016
    driver:
      email: 954209166228-compute@developer.gserviceaccount.com
      image_project: windows-cloud
      image_family: windows-2016
      disk_size: 50
      metadata:
        windows-startup-script-ps1: |
          winrm quickconfig -q
          winrm s winrm/config/winrs '@{MaxMemoryPerShellMB="512"}'
          winrm s winrm/config '@{MaxTimeoutms="1800000"}'
          winrm s winrm/config/service '@{AllowUnencrypted="true"}'
          winrm s winrm/config/service/auth '@{Basic="true"}'
          netsh firewall add portopening TCP 5985 "Port 5985"
          winrm s winrm/config/listener?Address=*+Transport=HTTP '@{Port="5985"}'
          get-service winrm

suites:
  - name: default
    run_list:
      - recipe[adjoin_fx::kitchen]
    attributes:
