---
driver:
  name: gce
  project: dazzlingwrench
  region: us-east1
  preemptible: true
  network: network

provisioner:
  name: chef_zero

transport:
  username: kitchenuser

platforms:
  - name: windows2012
    driver:
      email: 954209166228-compute@developer.gserviceaccount.com
      image_project: windows-cloud
      image_family: windows-2012-r2
      disk_size: 50

suites:
  - name: default
    run_list:
      - recipe[adjoin_fx::kitchen]
    attributes:
