---
driver:
  name: gce
  project: dazzlingwrench
  region: us-east1
  preemptible: false
  metadata:
    ssh-keys: <%= 'kitchenuser:' + IO.binread("/tmp/id_rsa.pub").rstrip! %>
  tags:
  - fxinnovation

provisioner:
  name: chef_zero
  max_retries: 3
  wait_for_retry: 90
  retry_on_exit_code:
  - 35
  client_rb:
    exit_status: :enabled
    client_fork: false

verifier:
  name: inspec
  sudo: true
  format: junit
  output: "%{platform}_%{suite}_inspec.xml"

transport:
  username: kitchenuser
  ssh_key: /tmp/id_rsa

platforms:
  - name: centos6
    driver:
      image_project: centos-cloud
      image_family: centos-6
  - name: centos7
    driver:
      image_project: centos-cloud
      image_family: centos-7
  - name: windows2008
    driver:
      email: 954209166228-compute@developer.gserviceaccount.com
      image_project: windows-cloud
      image_family: windows-2008-r2
      disk_size: 50
      metadata:
        windows-startup-script-ps1: |
          winrm quickconfig -q
          winrm s winrm/config/winrs '@{MaxMemoryPerShellMB="512"}'
          winrm s winrm/config '@{MaxTimeoutms="1800000"}'
          winrm s winrm/config/service '@{AllowUnencrypted="true"}'
          winrm s winrm/config/service/auth '@{Basic="true"}'
          netsh firewall add portopening TCP 5985 "Port 5985"
          winrm s winrm/config/listener?Address=*+Transport=HTTP '@{Port="5985"}'
          get-service winrm
  - name: windows2012
    driver:
      email: 954209166228-compute@developer.gserviceaccount.com
      image_project: windows-cloud
      image_family: windows-2012-r2
      disk_size: 50
      metadata:
        windows-startup-script-ps1: |
          winrm quickconfig -q
          winrm s winrm/config/winrs '@{MaxMemoryPerShellMB="512"}'
          winrm s winrm/config '@{MaxTimeoutms="1800000"}'
          winrm s winrm/config/service '@{AllowUnencrypted="true"}'
          winrm s winrm/config/service/auth '@{Basic="true"}'
          netsh firewall add portopening TCP 5985 "Port 5985"
          winrm s winrm/config/listener?Address=*+Transport=HTTP '@{Port="5985"}'
          get-service winrm
  - name: windows2016
    driver:
      email: 954209166228-compute@developer.gserviceaccount.com
      image_project: windows-cloud
      image_family: windows-2016
      disk_size: 50
      metadata:
        windows-startup-script-ps1: |
          winrm quickconfig -q
          winrm s winrm/config/winrs '@{MaxMemoryPerShellMB="512"}'
          winrm s winrm/config '@{MaxTimeoutms="1800000"}'
          winrm s winrm/config/service '@{AllowUnencrypted="true"}'
          winrm s winrm/config/service/auth '@{Basic="true"}'
          netsh firewall add portopening TCP 5985 "Port 5985"
          winrm s winrm/config/listener?Address=*+Transport=HTTP '@{Port="5985"}'
          get-service winrm

suites:
  - name: windows
    run_list:
      - recipe[adjoin_fx::kitchen]
    attributes:
      adjoin_fx:
        username: JoinDomain
        domain: c.dazzlingwrench.internal
        password: wSAE5Q7KHGJzeY8bMsPUwyFgqjR4pu2zUXB@G5eV9QHMwrxCB8S4Y3rL!ig6Vs3XYqvg
        server: activedirectory.c.dazzlingwrench.internal
    includes:
    - windows2016
    - windows2012
    - windows2008
    verifier:
      inspec_tests:
      - name: windows
        path: test/integration/windows
  - name: rhel
    run_list:
      - recipe[adjoin_fx::kitchen]
    attributes:
      adjoin_fx:
        username: JoinDomain
        domain: c.dazzlingwrench.internal
        server: activedirectory.c.dazzlingwrench.internal
        password: wSAE5Q7KHGJzeY8bMsPUwyFgqjR4pu2zUXB@G5eV9QHMwrxCB8S4Y3rL!ig6Vs3XYqvg
    includes:
    - centos7
    verifier:
      inspec_tests:
      - name: rhel
        path: test/integration/rhel
